/* Configuração: altere apenas estes valores para apontar para seu Worker.
 * O Worker deve expor GET /api/load, POST /api/demands, POST /api/log e POST /api/transfer.
 * GitHub (opcional no Worker): owner, repo e paths ficam aqui para referência.
 */
const CONFIG = Object.freeze({
  workerUrl: "https://seu-worker.workers.dev",
  github: { owner: "MarquesianoSecundaria", repo: "gestao-demandas", demandsPath: "demandas.json", auditPath: "log.json" },
  requestTimeout: 9000
});
const USERS = [
  { id: "miguel-marques", name: "Miguel Marques", role: "Administrador", admin: true },
  { id: "guilherme-pardo", name: "Guilherme Pardo", role: "Desenvolvedor", admin: false },
  { id: "gabriel-maciel", name: "Gabriel Maciel", role: "Desenvolvedor", admin: false },
  { id: "thaise-molon", name: "Thaise Molon", role: "Administrador", admin: true },
  { id: "quarto-desenvolvedor", name: "Quarto Desenvolvedor", role: "Desenvolvedor", admin: false }
];
const DEMO_DEMANDS = [
  { id: "d-101", type: "Supply", title: "Consolidar indicadores de ruptura", focalPoint: "ana", details: "Atualizar painel semanal.", reason: "Atualizar painel semanal.", area: "Supply", priority: "high", status: "in_progress", assignee: "ana", createdBy: "ana", updatedAt: "2026-09-24T14:00:00Z" },
  { id: "d-102", type: "Comercial", title: "Revisar política de descontos", focalPoint: "bruno", details: "Validar regras com comercial.", reason: "Validar regras com comercial.", area: "Comercial", priority: "medium", status: "backlog", assignee: "bruno", createdBy: "bruno", updatedAt: "2026-09-23T11:00:00Z" },
  { id: "d-103", type: "Financeiro", title: "Acesso ao relatório de margem", focalPoint: "carla", details: "", reason: "Acesso ao relatório de margem", area: "Financeiro", priority: "low", status: "done", assignee: "carla", createdBy: "carla", updatedAt: "2026-09-20T16:30:00Z" }
];
const STATUS = { backlog: "Backlog", in_progress: "Em andamento", blocked: "Bloqueada", done: "Concluída" };
const PRIORITY = { high: "Alta", medium: "Média", low: "Baixa" };
let state = { user: null, demands: [], audit: [], charts: {}, shas: { demands: null, log: null }, adminAll: true };
const $ = (selector) => document.querySelector(selector);
const esc = (value) => String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[c]));
const currentUser = () => USERS.find((user) => user.id === state.user) || USERS[0];
function showNotice(message, type = "error") { const el = $("#notice"); el.textContent = message; el.className = `notice ${type === "success" ? "success" : ""}`; el.hidden = false; setTimeout(() => { el.hidden = true; }, 6000); }
async function api(path, options = {}) {
  if (!CONFIG.workerUrl || CONFIG.workerUrl.includes("seu-worker")) throw new Error("Configure a URL do Cloudflare Worker em demandas/app.js.");
  const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), CONFIG.requestTimeout);
  try { const response = await fetch(`${CONFIG.workerUrl.replace(/\/$/, "")}${path}`, { ...options, headers: { "Content-Type": "application/json", ...(options.headers || {}) }, signal: controller.signal }); const body = response.status === 204 ? null : await response.json().catch(() => null); if (!response.ok) { const error = new Error(body?.error || `Worker respondeu ${response.status}.`); error.status = response.status; error.body = body; throw error; } return body; } catch (error) { if (error.name === "AbortError") throw new Error("Tempo esgotado ao comunicar com o Worker."); throw error; } finally { clearTimeout(timeout); }
}
function normalizeDemand(d) { const activityId = d.activityId || d.id || d._id; return { ...d, activityId, id: activityId, area: d.area || d.type || "", assignee: d.assignee || d.focalPoint || "", description: d.description ?? d.details ?? d.reason ?? "", updatedAt: d.updatedAt || d.updated_at || d.createdAt || new Date().toISOString(), createdBy: d.createdBy || d.created_by || d.actor || "" }; }
function visibleDemands() { const user = currentUser(); const owner = (value) => String(value || "").toLowerCase() === user.id.toLowerCase() || String(value || "").toLowerCase() === user.name.toLowerCase(); return state.demands.filter((d) => user.admin ? state.adminAll || owner(d.createdBy) : owner(d.createdBy)); }
function logEntry(action, demandId, detail) { return { action, demandId, detail, actor: currentUser().id, at: new Date().toISOString() }; }
async function postLog(entry) { const result = await api("/api/log", { method: "POST", body: JSON.stringify({ entry, expectedSha: state.shas.log }) }); state.shas.log = result?.version || state.shas.log; }
async function reloadAfterConflict() { showNotice("Conflito de versão detectado. Recarregando dados mais recentes…", "error"); await loadData(); }
async function loadData() {
  try { const data = await api("/api/load"); const payload = data?.data || data; const versions = payload.versions || {}; state.demands = (payload.demandas || []).map(normalizeDemand); state.audit = payload.log || []; state.shas.demands = versions.demandas || state.shas.demands; state.shas.log = versions.log || state.shas.log; showNotice("Dados sincronizados com o Worker.", "success"); }
  catch (error) { const cached = JSON.parse(localStorage.getItem("demandas-cache") || "null"); state.demands = (Array.isArray(cached) ? cached : cached?.demands) || DEMO_DEMANDS; if (cached?.shas) state.shas = cached.shas; showNotice(`Não foi possível carregar o Worker: ${error.message} Exibindo dados locais.`, "error"); }
  render();
}
function persistCache() { localStorage.setItem("demandas-cache", JSON.stringify({ demands: state.demands, shas: state.shas })); }
function render() { renderMetrics(); renderRecent(); renderTable(); renderAudit(); renderCharts(); updateUserUi(); }
function renderMetrics() { const demands = visibleDemands(); const counts = Object.keys(STATUS).map((status) => demands.filter((d) => d.status === status).length); $("#metrics").innerHTML = `<div class="metric"><span class="eyebrow">Total</span><strong>${demands.length}</strong><small>visíveis para você</small></div><div class="metric"><span class="eyebrow">Em andamento</span><strong>${counts[1]}</strong><small>em execução agora</small></div><div class="metric"><span class="eyebrow">Aguardando</span><strong>${counts[0]}</strong><small>no backlog</small></div><div class="metric"><span class="eyebrow">Concluídas</span><strong>${counts[3]}</strong><small>entregas realizadas</small></div>`; }
function demandRow(d, compact = false) { const person = USERS.find((u) => u.id === d.assignee); return compact ? `<div class="demand-row"><div><strong>${esc(d.title)}</strong><div class="subtle">${esc(d.area)} · ${esc(person?.name || "Não atribuído")}</div></div><span class="priority priority-${d.priority}">${PRIORITY[d.priority]}</span><span class="status status-${d.status}">${STATUS[d.status]}</span><span class="subtle">${formatDate(d.updatedAt)}</span></div>` : `<tr><td>${esc(d.title)}<div class="subtle">${esc(d.description || "Sem descrição")}</div></td><td>${esc(d.area)}</td><td><span class="priority priority-${d.priority}">${PRIORITY[d.priority]}</span></td><td><select class="status-select status status-${d.status}" data-action="status" data-id="${d.id}">${Object.entries(STATUS).map(([key, value]) => `<option value="${key}" ${key === d.status ? "selected" : ""}>${value}</option>`).join("")}</select></td><td>${esc(person?.name || "Não atribuído")}${currentUser().admin ? `<button class="tiny-btn" data-action="transfer" data-id="${d.id}" title="Transferir">↔</button>` : ""}</td><td>${formatDate(d.updatedAt)}</td><td><button class="tiny-btn" data-action="details" data-id="${d.id}">Abrir</button></td></tr>`; }
function renderRecent() { $("#recentList").innerHTML = visibleDemands().slice().sort((a, b) => new Date(b.updatedAt) - new Date(a.updatedAt)).slice(0, 4).map((d) => demandRow(d, true)).join("") || '<div class="empty">Nenhuma demanda registrada.</div>'; }
function renderTable() { const query = ($("#searchInput")?.value || "").toLowerCase(); const status = $("#statusFilter")?.value || ""; const priority = $("#priorityFilter")?.value || ""; const rows = visibleDemands().filter((d) => (!query || `${d.title} ${d.area} ${d.description}`.toLowerCase().includes(query)) && (!status || d.status === status) && (!priority || d.priority === priority)); $("#demandTable").innerHTML = rows.map((d) => demandRow(d)).join(""); $("#emptyState").hidden = rows.length > 0; }
function renderAudit() { $("#auditList").innerHTML = state.audit.length ? state.audit.slice(0, 30).map((item) => `<div class="audit-item"><time>${formatDate(item.at || item.createdAt)}</time><div><strong>${esc(item.action || "Atualização")}</strong><div class="subtle">${esc(item.detail || item.message || "")}</div></div></div>`).join("") : '<div class="empty">O Worker ainda não retornou eventos de auditoria.</div>'; }
function renderCharts() {
  if (!window.Chart) {
    document.querySelectorAll(".chart-fallback").forEach((x) => { x.hidden = false; });
    return;
  }
  const demands = visibleDemands();
  const statusData = Object.keys(STATUS).map((key) => demands.filter((d) => d.status === key).length);
  const priorityData = Object.keys(PRIORITY).map((key) => demands.filter((d) => d.priority === key).length);
  [["statusChart", "status", Object.values(STATUS), statusData, ["#b8c3cd", "#efa968", "#e57d89", "#42bca3"]], ["priorityChart", "priority", Object.values(PRIORITY), priorityData, ["#e57d89", "#efa968", "#63aaba"]]].forEach(([id, key, labels, data, colors]) => {
    if (state.charts[key]) state.charts[key].destroy();
    state.charts[key] = new Chart($(`#${id}`), {
      type: key === "status" ? "bar" : "doughnut",
      data: { labels, datasets: [{ data, backgroundColor: colors, borderWidth: 0, borderRadius: 5 }] },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { legend: { display: key !== "status", position: "bottom", labels: { usePointStyle: true, padding: 16 } } },
        scales: key === "status" ? { y: { beginAtZero: true, ticks: { stepSize: 1 } }, x: { grid: { display: false } } } : {}
      }
    });
  });
}
function updateUserUi() { const user = currentUser(); $("#roleBadge").textContent = user.role; document.querySelectorAll(".admin-only").forEach((el) => { el.hidden = !user.admin; }); let toggle = $("#adminScopeToggle"); if (user.admin && !toggle) { toggle = document.createElement("label"); toggle.id = "adminScopeToggle"; toggle.innerHTML = '<input type="checkbox" checked> Ver todas'; toggle.style.cssText = "font-size:11px;font-weight:600;display:flex;align-items:center;gap:4px"; $(".user-controls").append(toggle); toggle.querySelector("input").onchange = (e) => { state.adminAll = e.target.checked; render(); }; } if (toggle) toggle.hidden = !user.admin; $("#assigneeSelect").innerHTML = USERS.filter((u) => !u.admin).map((u) => `<option value="${u.id}">${u.name}</option>`).join(""); }
function formatDate(value) { return value ? new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short" }).format(new Date(value)).replace(".", "") : "—"; }
async function createDemand(form) { const demand = normalizeDemand({ activityId: `d-${Date.now()}`, type: form.area.value.trim(), title: form.title.value.trim(), focalPoint: form.assignee.value, details: form.description.value.trim(), reason: form.description.value.trim() || form.title.value.trim(), priority: form.priority.value, status: "backlog", createdBy: currentUser().id, updatedAt: new Date().toISOString() }); try { const result = await api("/api/demands", { method: "POST", body: JSON.stringify({ demand, expectedSha: state.shas.demands, actor: currentUser().id }) }); const saved = normalizeDemand(result?.demand || demand); state.shas.demands = result?.version || state.shas.demands; await postLog(logEntry("created", saved.activityId, `Demanda criada: ${saved.title}`)); showNotice("Demanda criada e registrada.", "success"); state.demands.unshift(saved); persistCache(); $("#demandDialog").close(); form.reset(); render(); } catch (error) { if (error.status === 409) return reloadAfterConflict(); showNotice(`Não foi possível salvar no Worker: ${error.message}`, "error"); } }
async function updateStatus(id, status) { const demand = state.demands.find((d) => d.activityId === id); if (!demand) return; const previous = demand.status; demand.status = status; demand.updatedAt = new Date().toISOString(); try { const result = await api("/api/demands", { method: "POST", body: JSON.stringify({ demand: { ...demand, activityId: id, status }, expectedSha: state.shas.demands, actor: currentUser().id }) }); Object.assign(demand, normalizeDemand(result?.demand || demand)); state.shas.demands = result?.version || state.shas.demands; await postLog(logEntry("status_updated", id, `${STATUS[previous]} → ${STATUS[status]}`)); showNotice("Status atualizado.", "success"); } catch (error) { demand.status = previous; if (error.status === 409) return reloadAfterConflict(); showNotice(`Não foi possível atualizar: ${error.message}`, "error"); } persistCache(); render(); }
async function transferDemand(id) { if (!currentUser().admin) return; const demand = state.demands.find((d) => d.activityId === id); const options = USERS.filter((user) => !user.admin).map((user) => `${user.id} (${user.name})`).join(", "); const assignee = window.prompt(`Informe o ID do novo responsável: ${options}`, demand?.assignee || ""); if (!assignee || !USERS.some((user) => user.id === assignee && !user.admin) || !demand) { if (assignee) showNotice("Responsável inválido. Use um dos IDs exibidos.", "error"); return; } const previous = demand.assignee; demand.assignee = assignee; demand.focalPoint = assignee; try { const result = await api("/api/transfer", { method: "POST", body: JSON.stringify({ activityId: id, destination: assignee, expectedDemandSha: state.shas.demands, expectedLogSha: state.shas.log, entry: logEntry("transferred", id, `Transferida para ${assignee}`) }) }); state.shas.demands = result?.versions?.demandas || state.shas.demands; state.shas.log = result?.versions?.log || state.shas.log; showNotice("Demanda transferida.", "success"); } catch (error) { demand.assignee = previous; demand.focalPoint = previous; if (error.status === 409) return reloadAfterConflict(); showNotice(`Não foi possível transferir: ${error.message}`, "error"); } persistCache(); render(); }
function exportCsv() { const header = ["id", "titulo", "area", "prioridade", "status", "responsavel", "atualizada"]; const rows = state.demands.map((d) => [d.id, d.title, d.area, PRIORITY[d.priority], STATUS[d.status], USERS.find((u) => u.id === d.assignee)?.name || "", d.updatedAt]); const csv = [header, ...rows].map((row) => row.map((cell) => `"${String(cell ?? "").replace(/"/g, '""')}"`).join(";")).join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob(["\ufeff" + csv], { type: "text/csv;charset=utf-8" })); link.download = `demandas-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(link.href); }
function setView(view) { document.querySelectorAll(".view").forEach((el) => { el.hidden = el.id !== `${view}View`; }); document.querySelectorAll(".nav-link").forEach((el) => el.classList.toggle("active", el.dataset.view === view)); $("#viewTitle").textContent = view === "dashboard" ? "Visão geral" : view === "demands" ? "Todas as demandas" : "Auditoria"; }
function init() { $("#dateLabel").textContent = new Intl.DateTimeFormat("pt-BR", { weekday: "long", day: "numeric", month: "long" }).format(new Date()); const saved = localStorage.getItem("demandas-user"); state.user = USERS.some((u) => u.id === saved) ? saved : USERS[0].id; $("#userSelect").innerHTML = USERS.map((u) => `<option value="${u.id}">${u.name}</option>`).join(""); $("#userSelect").value = state.user; $("#userSelect").onchange = (e) => { state.user = e.target.value; localStorage.setItem("demandas-user", state.user); render(); }; document.querySelectorAll("[data-view]").forEach((el) => el.onclick = () => setView(el.dataset.view)); ["#newDemandBtn", "#newDemandBtn2"].forEach((id) => $(id).onclick = () => $("#demandDialog").showModal()); $("#closeDialog").onclick = $("#cancelDialog").onclick = () => $("#demandDialog").close(); $("#demandForm").onsubmit = (e) => { e.preventDefault(); createDemand(e.target); }; ["#searchInput", "#statusFilter", "#priorityFilter"].forEach((id) => $(id).oninput = renderTable); $("#exportBtn").onclick = () => exportCsv(visibleDemands()); $("#demandTable").onclick = (e) => { const button = e.target.closest("[data-action]"); if (button?.dataset.action === "details") showNotice("Detalhe disponível no registro da demanda.", "success"); if (button?.dataset.action === "transfer") transferDemand(button.dataset.id); }; $("#demandTable").onchange = (e) => { if (e.target.dataset.action === "status") updateStatus(e.target.dataset.id, e.target.value); }; $("#configBtn").onclick = () => { $("#configText").innerHTML = `<strong>Worker URL:</strong> <code>${esc(CONFIG.workerUrl)}</code><br><strong>GitHub:</strong> ${esc(CONFIG.github.owner)}/${esc(CONFIG.github.repo)}<br><strong>Paths:</strong> ${esc(CONFIG.github.demandsPath)} / ${esc(CONFIG.github.auditPath)}<br><br>Edite <code>demandas/app.js</code> para configurar o ambiente.`; $("#configDialog").showModal(); }; updateUserUi(); loadData(); }
document.addEventListener("DOMContentLoaded", init);
